export const AUDIT_ACTIONS = {
    ROLE_CHANGED: 'ROLE_CHANGED',
    MEMBER_INVITED: 'MEMBER_INVITED',
    MEMBER_REMOVED: 'MEMBER_REMOVED',
    DEPARTMENT_HEAD_CHANGED: 'DEPARTMENT_HEAD_CHANGED',
    COMPLAINT_RESOLVED: 'COMPLAINT_RESOLVED',
    COMPLAINT_DISMISSED: 'COMPLAINT_DISMISSED',
    CALIBRATION_FINALIZED: 'CALIBRATION_FINALIZED',
    REVIEW_CYCLE_ACTIVATED: 'REVIEW_CYCLE_ACTIVATED',
    REVIEW_CYCLE_COMPLETED: 'REVIEW_CYCLE_COMPLETED',
    REVIEW_CYCLE_CALIBRATING: 'REVIEW_CYCLE_CALIBRATING',
    TARGET_DELETED: 'TARGET_DELETED',
    TASK_REASSIGNED: 'TASK_REASSIGNED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];